### ISSUE TITLE
undefined reference to `FT6336U::FT6336U(signed char, signed char, unsigned char, unsigned char)'

### ISSUE THREAD

**Issue by MickeyGentry** [aselectroworks/Arduino-FT6336U#10]
I am running the ReadTouchParam.ino example without changes with a Teensy board but it won't compile. The complete error message is:

```
/Users/michaelg3933/Library/Arduino15/packages/teensy/tools/teensy-compile/11.3.1/arm/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: /Users/michaelg3933/Library/Caches/arduino/sketches/6E53364BAA818548E3207153B781C12F/sketch/ReadTouchParam.ino.cpp.o: in function `_GLOBAL__sub_I_ft6336u':
/Users/michaelg3933/Documents/Arduino/libraries/FT6336U_CTP_Controller/examples/ReadTouchParam/ReadTouchParam.ino:8: undefined reference to `FT6336U::FT6336U(signed char, signed char, unsigned char, unsigned char)'
collect2: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1
```

The error seems to emanate from the class FT6336U:

```
#if defined(ESP32) || defined(ESP8266) 
    FT6336U(int8_t sda, int8_t scl, uint8_t rst_n, uint8_t int_n);
#endif
```

Which makes sense since I'm not using an ESP board.

I made the following changes but got the same error:

```
#if defined(ARDUINO_TEENSY41)
    FT6336U(int8_t sda, int8_t scl, uint8_t rst_n, uint8_t int_n);
#endif
```
Also tried...
```
#ifdef ARDUINO_TEENSY41
    FT6336U(int8_t sda, int8_t scl, uint8_t rst_n, uint8_t int_n);
#endif
```

I tested that conditional in the Arduino IDE (which I'm using for this example) and it returns true. I also removed the conditional entirely:

```
//#if defined(ESP32) || defined(ESP8266) 
    FT6336U(int8_t sda, int8_t scl, uint8_t rst_n, uint8_t int_n);
//#endif
```

No change, same error as above for "undefined reference."

What am I missing?

Thanks for any help!

**Comment by aselectroworks** [comment]
@MickeyGentry I fixed Teensyduino support and pushed it. 
Please check https://github.com/aselectroworks/Arduino-FT6336U/commit/a439f3963c2ba85954debb880c84e35944d362a7

**Comment by MickeyGentry** [comment]
Thank you very much! All working as expected.
