### ISSUE TITLE
read_touch1_weight() not giving data

### ISSUE THREAD

**Issue by videobuff** [aselectroworks/Arduino-FT6336U#2]
Hello,
I use your library for a project, but I have a few issues.
I find that the value read_touch1_weight()never gives data. 
Also, if the display is at rest, it still shows random touch events with ft6336u.read_touch1_event().
Finally, is it possible to have the display start at x=0 and y = 0 ? 
Thanks very much. Attached is a small sketch to demonstrate this on a WT32-SCO1 display. Your library is advised by the manufacturer.

Erik, PA0ESH
[WT32-SCO1-ReadTouchParam.ino.ino.zip](https://github.com/aselectroworks/Arduino-FT6336U/files/8055283/WT32-SCO1-ReadTouchParam.ino.ino.zip)

**Comment by aselectroworks** [comment]
@videobuff
I think FT6336U have firmware inside IC. 
So the behavior of FT6336U depends on its firmware. 

I advice you to contact with the supplier of WT32-SC01.

**Comment by videobuff** [comment]
Thank you for the reply. I did contact them but they said that the FT6336U is the official library. I found that the FT6336 Library works when I hard code the SCL and SDA PINS (18 & 19). Then the values are stable   So the firmware has nothing to do with it in my opinion. Anyhow thank you.
