### ISSUE TITLE
How to Rotate the touch input?

### ISSUE THREAD

**Issue by MikeyMoMo** [aselectroworks/Arduino-FT6336U#3]
I am using a WT32-SC01 board.  I have this working with TFT_eSPI library for display and your library for touch.  I need to rotate the touch input to match the screen rotation.  How may I do that?  Still seems to be some minor issues but none that affect me at the moment.  I just need X and Y of the touch.  The current rotation is where the power connector is on the left of the WT32. I don't see any routine for rotation.

Thanks for the library!!

Mike

**Comment by aselectroworks** [comment]
Hi @MikeyMoMo 
Currently, this library does not support screen rotation. So you need to convert coordinates by yourself.

**Comment by MikeyMoMo** [comment]
I have been looking for a routine to do that instead of reinventing it myself.  Do you know of any.  I don't mind doing it but perfecting it seems a little difficult.

**Comment by aselectroworks** [comment]
I don't have a routine for you. 
I think you can refer to [Rotation of axes](https://en.wikipedia.org/wiki/Rotation_of_axes) article of wikipedia.

**Comment by MikeyMoMo** [comment]
Will read that.  Thanks. I had searched a lot but not including axes.  I
really wish Bodmer to include this in his great library.

**Comment by MarcelRobitaille** [comment]
@MikeyMoMo  You can check out how the Adafruit GFX library does it: https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_GFX.cpp

```cpp
switch (rotation) {
    case 1:
      t = x;
      x = WIDTH - 1 - y;
      y = t;
      break;
    case 2:
      x = WIDTH - 1 - x;
      y = HEIGHT - 1 - y;
      break;
    case 3:
      t = x;
      x = y;
      y = HEIGHT - 1 - t;
      break;
    }
```

**Comment by MikeyMoMo** [comment]
Sadly, the touch controller has quit working on the unit I wanted to rotate
but this is good information to keep on hand.  Thank you for this.  It
might come in handy in the future.

The articles I had read on this went into some complex math explanations
but it seems to be so easy with this code. I appreciate your response.
